name: sufenbao
description: sufenbao
version: 3.2.0+102

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  #  flutter_qq_ads: ^2.5.0
  #  weibo_kit: ^4.0.0
  #  tencent_kit: ^5.0.2
  hugeicons: ^0.0.11
  flutter_z_location:
    path: ./plugins/flutter_z_location
  qr_flutter: ^4.1.0
  image_gallery_saver_plus2: ^4.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.1.1
  dio: ^5.4.3+1
  shared_preferences: ^2.1.0
  cached_network_image: ^3.3.1
  maixs_utils:
    path: package/maixs_utils
  settings_ui: ^2.0.2
  pinput: ^4.0.0
  awesome_dialog: ^3.2.0
  clipboard: ^0.1.3
  flutter_native_splash: ^2.2.12
  flutter_picker:
    path: package/flutter_picker
  #  flutter_swiper: ^1.1.6
  flutter_swiper:
    path: package/flutter_swiper
  common_utils: 2.1.0
  keyboard_actions: ^4.0.1
  sticky_headers: ^0.3.0+2
  animations: ^2.0.7
  flutter_switch: ^0.3.2
  flutter_slidable: ^3.1.0
  in_app_purchase: ^3.2.0
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  shake_animation_widget: ^3.0.3
  dotted_border: ^2.0.0+3
  flutter_pdfview: 1.3.2
  #屏幕适配
  flutter_screenutil: ^5.9.0
  animated_text_kit: ^4.2.2
  tobias: ^5.1.1
  #  tobias:
  #    git:
  #      url: https://gitee.com/jacky4631/tobias.git
  flutter_alibc:
    #    path: ../flutter_alibc_kit
    git:
      url: https://gitee.com/jacky4631/flutter_alibc_kit.git
      ref: master
  decimal: ^2.3.0
  chewie: ^1.8.1
  shimmer: ^3.0.0
  data_table_2: 2.3.12
  signature: ^5.3.2
  encrypt: ^5.0.3
  connectivity_plus: ^6.0.3
  webview_flutter: ^4.2.1
  device_info_plus: ^10.1.0
  url_strategy: ^0.2.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.0
  url_launcher_ios: ^6.3.1
  appcheck: 1.1.0
  wechat_assets_picker: ^9.1.0
  wechat_camera_picker: ^4.3.1
  #  flutter_swiper: ^1.1.6
  fluwx: ^4.5.6
  flutter_inappwebview: ^6.1.4
  image_cropper: 8.0.2
  package_info_plus: ^8.0.2
  jpush_flutter: ^3.2.7
  sign_in_with_apple: ^6.1.3
  pay_ios: ^1.0.7
  photo_manager: ^3.5.2
  flutter_ali_face_verify:
        path: ./plugins/flutter_ali_face_verify
#    git:
#      url: https://gitee.com/jacky4631/flutter_ali_face_verify.git
  shanyan:
        path: ./plugins/CLShanYan_Flutter/shanyan
#    git:
#      url: https://gitee.com/jacky4631/CLShanYan_Flutter.git
#      path: shanyan
#      ref: v2.3.4.5
  flutter_plugin_android_lifecycle: ^2.0.28
  geolocator_android: 4.5.4
  geolocator: 11.0.0


  dart_date: ^1.5.3
  dart_json_mapper: ^2.2.16
  gap: ^3.0.1
  #电池优化，防止通知被杀死
  disable_battery_optimizations_latest: ^1.0.0


  auto_route: ^9.2.2
  flutter_staggered_grid_view: ^0.7.0
  flex_color_scheme: ^8.2.0
  extended_tabs: ^5.0.0
  easy_refresh: ^3.4.0
  ali_auth: ^1.3.5
  flutter_base:
    path: ../plugins/flutter_base

  # 模型处理
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  json_annotation: ^4.9.0
  copy_with_extension: any



dev_dependencies:
  mockito: ^5.4.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.13.1

  json_serializable: ^6.9.0
  copy_with_extension_gen: any

  flutter_gen_runner: ^5.10.0
  auto_route_generator: ^9.0.0


  riverpod_generator: ^2.6.3


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1024.png"
flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/
    - assets/images/cash/
    - assets/images/share/
    - assets/images/mall/
    - assets/images/me/
    - assets/images/lv/
    - assets/images/menu/
    - assets/images/help/
    - assets/key/
  fonts:
    - family: BaoIcons
      fonts:
        - asset: assets/fonts/icomoon.ttf

flutter_intl:
  enabled: true