name: maixs_utils
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.0 <=3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_styled_toast: ^2.1.3
  dio: 4.0.6
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+2
  multi_image_picker: ^4.6.3
  shared_preferences: ^2.1.0
  # flutter_html: ^2.0.0-nullsafety.0
  # flutter_html: 2.0.0
  # ^0.19.1
  flutter_svg: ^2.0.4
  url_launcher: 6.1.10
  #^1.1.2
  shimmer: ^2.0.0
  # ^0.9.2
  photo_view: ^0.14.0
  # loading_indicator: ^1.2.0
  waterfall_flow: 3.0.2
  wechat_assets_picker: ^8.4.1
  image_crop: ^0.4.1
  encrypt: 5.0.1
  device_info_plus: ^8.2.0
  photo_manager: ^2.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
   - assets/svg/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
